# Generated by Django 4.0.4 on 2022-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caractaires', models.CharField(max_length=100)),
                ('chassis', models.CharField(max_length=100)),
                ('box', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('anomalies', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etat_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteres', models.CharField(max_length=100)),
                ('chassis', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('boxage', models.CharField(max_length=100)),
                ('immat', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('categorie', models.CharField(max_length=100)),
                ('kilometrage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caractaires', models.CharField(max_length=100)),
                ('chassis', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('heure', models.CharField(max_length=100)),
                ('transport', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caractaires', models.CharField(max_length=100)),
                ('chassis', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('origine', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('heure', models.CharField(max_length=100)),
                ('transport', models.CharField(max_length=100)),
            ],
        ),
    ]
